## Step 1: Import relevant libraries

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Step 2: Load the dataset

In [4]:
sales_df = pd.read_excel("../data/dirty_supplement_sales_data_2020.xlsx")

sales_df.head()

,Date,Product Category,Product Name,Units Sold,Units Returned,Price,Discount (%),Revenue,Platform,Location
0,2020-10-07,Sleep Aids,ImmunoPro,NaN,1.0,$10.99,105.0,0.000,Instore,Los Angeles
1,2020-09-16,Vitamins,MuscleMax,NaN,-1.0,NaN,0.0,NaN,Mob App,Houston
2,2020-11-11,Immunity Boosters,Slim F@st,15.0,-1.0,15,NaN,225.000,Online,Chicago
3,2020-11-04,Energy Drinks,PowerFuel,14.0,0.0,$10.99,25.0,115.395,Online,new york
4,2020-06-03,Vitamins,SuperV!ta,NaN,NaN,$10.99,50.0,0.000,Mobile App,new york

## Step 3: Inspecting the data

View the top and last rows

In [9]:
# Top 5 rows
print(f"Top 5 Rows: {display(sales_df.head())}")

print()

# Bottom 5 rows
print(f"Bottom 5 Rows: {display(sales_df.tail())}")

,Date,Product Category,Product Name,Units Sold,Units Returned,Price,Discount (%),Revenue,Platform,Location
0,2020-10-07,Sleep Aids,ImmunoPro,NaN,1.0,$10.99,105.0,0.000,Instore,Los Angeles
1,2020-09-16,Vitamins,MuscleMax,NaN,-1.0,NaN,0.0,NaN,Mob App,Houston
2,2020-11-11,Immunity Boosters,Slim F@st,15.0,-1.0,15,NaN,225.000,Online,Chicago
3,2020-11-04,Energy Drinks,PowerFuel,14.0,0.0,$10.99,25.0,115.395,Online,new york
4,2020-06-03,Vitamins,SuperV!ta,NaN,NaN,$10.99,50.0,0.000,Mobile App,new york

Top 5 Rows: None

,Date,Product Category,Product Name,Units Sold,Units Returned,Price,Discount (%),Revenue,Platform,Location
3095,2020-09-16,Immunity Boosters,SuperV!ta,10.0,2.0,NaN,25.0,NaN,In-Store,Chicago
3096,2020-08-12,Vitamins,DreamRest,25.0,0.0,NaN,25.0,NaN,onlien,New York
3097,2020-10-21,Immunity Boosters,SuperV!ta,NaN,-1.0,$10.99,25.0,0.0,Mobile App,Chi-Town
3098,2020-02-19,Weight Loss,SuperVita,NaN,NaN,NaN,NaN,NaN,Instore,Chicago
3099,2020-08-26,Protein,PowerFuel,NaN,0.0,15,0.0,0.0,Mobile App,Phoenix

Bottom 5 Rows: None

__Inspecting the shape of the dataset__

In [10]:
# .shape attribute
sales_df.shape

(3100, 10)